/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package godofwar;

/**
 *
 * @author Utente
 */
public class FormPersonaggio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPersonaggio.class.getName());

    /**
     * Creates new form FormPersonaggio
     */
    public FormPersonaggio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Utente\\Desktop\\Progetto-GDR God of War\\Freya_Render_God_Of_War_2018.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 280, 380, 380);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Utente\\Desktop\\Progetto-GDR God of War\\Not_atreus_of_sparta.webp-removebg-preview.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(420, 180, 400, 420);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Utente\\Desktop\\Progetto-GDR God of War\\immagini\\Kratos_PS4.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(860, 290, 260, 420);

        jButton1.setBackground(new java.awt.Color(126, 89, 80));
        jButton1.setFont(new java.awt.Font("Kratos TrueType - GOD $ WAR", 0, 14)); // NOI18N
        jButton1.setText("Atreus");
        getContentPane().add(jButton1);
        jButton1.setBounds(480, 590, 140, 23);

        jButton2.setBackground(new java.awt.Color(126, 89, 80));
        jButton2.setFont(new java.awt.Font("Kratos TrueType - GOD $ WAR", 0, 12)); // NOI18N
        jButton2.setText("KRATOS");
        getContentPane().add(jButton2);
        jButton2.setBounds(920, 730, 150, 23);

        jButton3.setBackground(new java.awt.Color(126, 89, 80));
        jButton3.setFont(new java.awt.Font("Kratos TrueType - GOD $ WAR", 0, 12)); // NOI18N
        jButton3.setText("FREYA");
        getContentPane().add(jButton3);
        jButton3.setBounds(70, 710, 150, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Utente\\Desktop\\Progetto-GDR God of War\\Gemini_Generated_Image_75ru3y75ru3y75ru.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-160, -220, 1470, 1230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPersonaggio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
