/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package godofwar;

/**
 *
 * @author Utente
 */
public class FormPersonaggio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPersonaggio.class.getName());

    /**
     * Creates new form FormPersonaggio
     */
    public FormPersonaggio() {
        Personaggio p;
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_freya = new javax.swing.JLabel();
        lbl_atreus = new javax.swing.JLabel();
        lbl_kratos = new javax.swing.JLabel();
        btm_atreus = new javax.swing.JButton();
        btm_kratos = new javax.swing.JButton();
        btm_freya = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbl_freya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/Freya_Render_God_Of_War_2018.png"))); // NOI18N
        getContentPane().add(lbl_freya);
        lbl_freya.setBounds(40, 280, 380, 380);

        lbl_atreus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/Not_atreus_of_sparta.webp-removebg-preview.png"))); // NOI18N
        getContentPane().add(lbl_atreus);
        lbl_atreus.setBounds(420, 180, 400, 420);

        lbl_kratos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/Kratos_PS4.png"))); // NOI18N
        getContentPane().add(lbl_kratos);
        lbl_kratos.setBounds(860, 290, 260, 420);

        btm_atreus.setBackground(new java.awt.Color(126, 89, 80));
        btm_atreus.setFont(new java.awt.Font("Kratos TrueType - GOD $ WAR", 0, 14)); // NOI18N
        btm_atreus.setText("Atreus");
        btm_atreus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_atreusActionPerformed(evt);
            }
        });
        getContentPane().add(btm_atreus);
        btm_atreus.setBounds(480, 590, 140, 23);

        btm_kratos.setBackground(new java.awt.Color(126, 89, 80));
        btm_kratos.setFont(new java.awt.Font("Kratos TrueType - GOD $ WAR", 0, 12)); // NOI18N
        btm_kratos.setText("KRATOS");
        btm_kratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_kratosActionPerformed(evt);
            }
        });
        getContentPane().add(btm_kratos);
        btm_kratos.setBounds(920, 730, 150, 23);

        btm_freya.setBackground(new java.awt.Color(126, 89, 80));
        btm_freya.setFont(new java.awt.Font("Kratos TrueType - GOD $ WAR", 0, 12)); // NOI18N
        btm_freya.setText("FREYA");
        btm_freya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_freyaActionPerformed(evt);
            }
        });
        getContentPane().add(btm_freya);
        btm_freya.setBounds(70, 710, 150, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/Gemini_Generated_Image_75ru3y75ru3y75ru.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-160, -220, 1470, 1230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btm_freyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_freyaActionPerformed
       Personaggio p1 = new Personaggio("Freya",100,10,"somma",20);
       FormGioco fg = new FormGioco(p1);
       fg.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btm_freyaActionPerformed

    private void btm_atreusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_atreusActionPerformed
       Personaggio p2 = new Personaggio("Atreus",100,10,"moltilplica",2);
       FormGioco fg = new FormGioco(p2);
       fg.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btm_atreusActionPerformed

    private void btm_kratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_kratosActionPerformed
       Personaggio p3 = new Personaggio("Kratos",120,10,"moltiplica",2);
       p3.setVita(140);
       FormGioco fg = new FormGioco(p3);
       fg.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btm_kratosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPersonaggio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_atreus;
    private javax.swing.JButton btm_freya;
    private javax.swing.JButton btm_kratos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_atreus;
    private javax.swing.JLabel lbl_freya;
    private javax.swing.JLabel lbl_kratos;
    // End of variables declaration//GEN-END:variables
}
