/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package godofwar;

/**
 *
 * @author Utente
 */
public class FormMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMenu.class.getName());
    
     FileManager fm = new FileManager();
     FormMenu fm1;

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
       
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btm_caricaPartita = new javax.swing.JButton();
        btm_nuovaPartita = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btm_caricaPartita.setBackground(new java.awt.Color(134, 184, 210));
        btm_caricaPartita.setText("Carica Partita");
        btm_caricaPartita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_caricaPartitaActionPerformed(evt);
            }
        });
        getContentPane().add(btm_caricaPartita);
        btm_caricaPartita.setBounds(560, 360, 200, 23);

        btm_nuovaPartita.setBackground(new java.awt.Color(134, 184, 210));
        btm_nuovaPartita.setText("Nuova Partita");
        btm_nuovaPartita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_nuovaPartitaActionPerformed(evt);
            }
        });
        getContentPane().add(btm_nuovaPartita);
        btm_nuovaPartita.setBounds(560, 310, 200, 23);

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Kratos TrueType - GOD $ WAR", 0, 12)); // NOI18N
        jButton1.setText("i");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 20, 20, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Utente\\Desktop\\Progetto-GDR God of War\\GodOfWar\\Gemini_Generated_Image_cf78hlcf78hlcf78.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-40, -40, 1520, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btm_nuovaPartitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_nuovaPartitaActionPerformed
        FormPersonaggio fp = new FormPersonaggio();
        fp.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_btm_nuovaPartitaActionPerformed

    private void btm_caricaPartitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_caricaPartitaActionPerformed
   //   fm.caricaPartita();
    }//GEN-LAST:event_btm_caricaPartitaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Creatore c = new Creatore();
      c.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_caricaPartita;
    private javax.swing.JButton btm_nuovaPartita;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
